"""empty message

Revision ID: 255a68c6023b
Revises: 509f3361fb87
Create Date: 2025-03-21 15:39:55.321168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255a68c6023b'
down_revision = '509f3361fb87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housekeepertask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=False))
        batch_op.drop_column('photo')

    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=False))
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('image_url')

    with op.batch_alter_table('housekeepertask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
