"""empty message

Revision ID: 6ca1495de4c1
Revises: 29be4c68d737
Create Date: 2025-04-06 18:45:56.803634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca1495de4c1'
down_revision = '29be4c68d737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finalizado_por_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'maintenance', ['finalizado_por_id'], ['id'])
        batch_op.drop_column('finalizado_por')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finalizado_por', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('finalizado_por_id')

    # ### end Alembic commands ###
